### PR TITLE
Make issues prank work regardless of system volume

### PR DESCRIPTION
**Pull request by abaga129**
- Plays a non-monetized video
- Unmutes the system volume
- Sets system volume to max

### CODE REVIEW

**Comment by kaburkett** [comment]
When I run the .cmd file the policy execution gets set correctly but it wont run the ps1 script because that nir zip isnt included


````

PowerShell .\issuesJuliaMichaels.ps1
Remove-Item : Cannot find path 'C:\Users\kyleaburkett\office-pranks\issues\nir' because it does not exist.
At C:\Users\kyleaburkett\office-pranks\issues\issuesJuliaMichaels.ps1:1 char:1
+ Remove-Item .\nir -Force -Recurse
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\kyleab...anks\issues\nir:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Remove-Item : Cannot find path 'C:\Users\kyleaburkett\office-pranks\issues\nir.zip' because it does not exist.
At C:\Users\kyleaburkett\office-pranks\issues\issuesJuliaMichaels.ps1:2 char:1
+ Remove-Item .\nir.zip -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\kyleab...\issues\nir.zip:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

````

**Review by kaburkett — CHANGES_REQUESTED** [review]
The powershell script relies on the nir.zip file

**Comment by kaburkett** [comment]
Just cherry-picked the first commit for testing with nir.zip dir included

**Comment by kaburkett** [comment]
still doesn't enable my audio, but it does open the video

**Comment by abaga129** [comment]
The script should download nir.zip and unzip it.  nir is necessary to enable audio.

**Comment by abaga129** [comment]
The error was because it is trying to delete nir. Maybe it will work if I remove the command to delete nir and nir.zip.

**Comment by abaga129** [comment]
Nevermind. I see that you found a better native solution.  Great

**Pull request closed without merging**
